### PR TITLE
Upgrade selector regex

### LINKED ISSUE #4: CSS-Processor: Don't process file extensions in url('...')
Example:
```
@font-face {
    font-family: 'Roboto';
    src: url('/fonts/Roboto-Regular-webfont.eot');
    src: url('/fonts/Roboto-Regular-webfont.eot?#iefix') format('embedded-opentype'),
    url('/fonts/Roboto-Regular-webfont.woff') format('woff'),
    url('/fonts/Roboto-Regular-webfont.ttf') format('truetype'),
    url('/fonts/Roboto-Regular-webfont.svg#RobotoRegular') format('svg');
    font-weight: normal;
    font-style: normal;
}
```

Will become:
```
@font-face {
    font-family: 'Roboto';
    src: url('/fonts/Roboto-Regular-webfont.a');
    src: url('/fonts/Roboto-Regular-webfont.a?#iefix') format('embedded-opentype'),
    url('/fonts/Roboto-Regular-webfont.b') format('woff'),
    url('/fonts/Roboto-Regular-webfont.c') format('truetype'),
    url('/fonts/Roboto-Regular-webfont.d#RobotoRegular') format('svg');
    font-weight: normal;
    font-style: normal;
}
```

Of course one can ignore them, but... it would be a nice feature.

### PR DESCRIPTION
**Pull request by hashworks**
This resolves #4.

I'm not sure how to run the test suit, I'll just hope this will be tested in here.

EDIT: Ok, I'll take a look at that later.

### CODE REVIEW

**Comment by calebthebrewer** [comment]
Negative lookbehinds aren't support in JS RegExp yet, unfortunately. Another approach we could take is to validate the characters after the selector (such as : , > ~ + [), but that may still not cover all cases.

**Comment by hashworks** [comment]
Any idea why the id selector tests fail @calebthebrewer?

Also I think we can drop the `A hash value should return a match which include the close bracket` test because we look for the `{` suffix.

**Comment by hashworks** [comment]
Now the only problem is that hex values in a single line followed by a opening bracket somewhere get matched, so we need to match the valid characters after the tag as well.

**Comment by hashworks** [comment]
Seems like the lookahead for `{` is problematic then the `{` is on the next line. Don't merge!

Also a friend of mine just told me about those uncommon selectors:
```
[id=my-Address] {}
[id*=s] {}
[class=my-city] {}
[class*=y] {}
```

I'll have to adjust the regex for those two.

**Comment by hashworks** [comment]
Ok, seems like the single line modifier is unsupported. Let's replace that one...

**Comment by hashworks** [comment]
Yup, that should do @calebthebrewer. Did I miss any suffix characters?
`\s` `:` `#` `.` `{` `,` `>` `~` `+` `[` `]`

**Comment by calebthebrewer** [comment]
Looks like you got everything I'm familiar with, thanks @hashworks.

**Pull request merged**
